import {
  EASE_SPRING_CSS,
  FILL_TONES,
  palette,
  shape,
  type ThemeColors,
} from "./tokens";

function colorVars(colors: ThemeColors, indent: string): string {
  const base = [
    ["background", colors.background],
    ["surface", colors.surface],
    ["ink", colors.ink],
    ["muted", colors.muted],
    ["outline", colors.outline],
    ["on-fill", colors.onFill],
    ["on-fill-muted", colors.onFillMuted],
  ];
  const fills = FILL_TONES.map((tone) => [`fill-${tone}`, colors[tone]]);
  return [...base, ...fills]
    .map(([name, value]) => `${indent}--tn-${name}: ${value};`)
    .join("\n");
}

const shapeVars = [
  `  --tn-border-width: ${shape.borderWidth};`,
  `  --tn-radius-sticker: ${shape.radiusSticker};`,
  `  --tn-radius-control: ${shape.radiusControl};`,
  `  --tn-radius-card: ${shape.radiusCard};`,
  `  --tn-shadow-sm: ${shape.shadowSm};`,
  `  --tn-shadow: ${shape.shadow};`,
  `  --tn-shadow-lg: ${shape.shadowLg};`,
  `  --tn-ease-spring: ${EASE_SPRING_CSS};`,
].join("\n");

/**
 * Renders `src/app/tokens.css` from `tokens.ts` (single source of truth).
 * Run `bun run tokens` to regenerate after editing tokens.
 */
export function renderTokensCss(): string {
  return `/* Generated by scripts/generate-tokens-css.ts - do not edit by hand. */
:root,
[data-theme="light"] {
${colorVars(palette.light, "  ")}
${shapeVars}
  color-scheme: light;
}

[data-theme="dark"] {
${colorVars(palette.dark, "  ")}
  color-scheme: dark;
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
${colorVars(palette.dark, "    ")}
    color-scheme: dark;
  }
}
`;
}
